CREATE TABLE devices (
    token UUID PRIMARY KEY,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE blood_pressure_readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_token UUID NOT NULL,
    client_id VARCHAR(255) NOT NULL,
    taken_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    systolic INTEGER NOT NULL,
    diastolic INTEGER NOT NULL,
    heart_rate INTEGER,
    note VARCHAR(1000),
    client_updated_at TIMESTAMP(6) WITH TIME ZONE,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    server_updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_bp_device_client UNIQUE (device_token, client_id)
);

CREATE TABLE weight_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_token UUID NOT NULL,
    client_id VARCHAR(255) NOT NULL,
    taken_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    grams INTEGER NOT NULL,
    note VARCHAR(1000),
    client_updated_at TIMESTAMP(6) WITH TIME ZONE,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    server_updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_weight_device_client UNIQUE (device_token, client_id)
);
